name: Build and stage

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: '8.0'

jobs:
  build:
    name: Build and publish app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Generate API browser docs
      run: |
        cd src/api-browser-generation
        ./build-metadata.ps1
        cd ../Client
        ./process-api-browser-files.ps1

    - name: dotnet build
      run: dotnet build src/Client --configuration Release

    - name: dotnet publish
      run: dotnet publish src/Client --configuration Release --no-build --output ${{ env.DOTNET_ROOT }}/mainsite

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: Steeltoe-MainSite
        path: ${{ env.DOTNET_ROOT }}/mainsite

  deploy:
    name: Deploy
    if: ${{ github.secret_source == 'Actions' }}
    environment:
      name: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || vars.STAGING_SLOT_NAME }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      SLOT_NAME: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || vars.STAGING_SLOT_NAME }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: Steeltoe-MainSite

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: If PR, create a new staging slot
      if: ${{ github.event_name == 'pull_request' }}
      run: az webapp deployment slot create --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME}} --slot ${{ env.SLOT_NAME }} --configuration-source ${{ vars.STAGING_SLOT_NAME }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: ${{ env.SLOT_NAME }}

    - name: If PR, comment with the preview link
      if: ${{ github.event_name == 'pull_request' }}
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          ## Preview link: https://${{ vars.AZURE_WEBAPP_NAME }}-${{ env.SLOT_NAME }}.azurewebsites.net

          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          ### Need to pair with a custom docs site address?

          A team member can use this az CLI command, replacing <this-PR-number> and <other-pr-number> for valid numbers:
          ```bash
          az webapp config appsettings set --resource-group steeltoe --name www-steeltoe --slot pr-<this-PR-number> --settings DocsSite__BaseAddress=https://docs-steeltoe-pr-<other-pr-number>.azurewebsites.net
          ```

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
