name: Deploy PR to staging env

on:
  push:
    branches: [ "v4" ]
  pull_request:
    branches:
    - main

concurrency: ci-${{ github.event.number }}

env:
  AZURE_WEBAPP_NAME: steeltoe-mainsite
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0'
  RESOURCE_GROUP: steeltoe
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build src/Client --configuration Release
      - name: dotnet publish
        run: dotnet publish src/Client -c Release -o ${{env.DOTNET_ROOT}}/mainsite
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: Steeltoe-MainSite
          path: ${{env.DOTNET_ROOT}}/mainsite
  
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $AZURE_WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: Steeltoe-MainSite
    
    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name:  ${{ env.SLOT_NAME }}
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.AZURE_WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
   