name: Deploy a preview environment

on:
  pull_request:
    branches:
    - main
    - v4

concurrency: ci-${{ github.event.number }}

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0'
  SLOT_NAME: preview-${{ github.event.number }}

jobs:
  build:
    name: Build and publish app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build src/Client --configuration Release
      - name: dotnet publish
        run: dotnet publish src/Client -c Release -o ${{ env.DOTNET_ROOT }}/mainsite
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: Steeltoe-MainSite
          path: ${{ env.DOTNET_ROOT }}/mainsite

  set-up-test-env:
    name: Create a staging slot for this PR
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_WEBAPP_NAME}} --slot $SLOT_NAME

  deploy:
    name: Deploy to new staging slot
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: Steeltoe-MainSite

    - name: Log into Azure CLI with service principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with: 
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name:  ${{ env.SLOT_NAME }}
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          ## Preview link: https://${{ vars.AZURE_WEBAPP_NAME }}-${{ env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
   